openapi: 3.0.2
info: 
  title: stupid-backend
  license:
    name: MIT License
    url: https://github.com/CalebQ42/stupid-backend/blob/main/LICENSE
  version: 1.0.0
components:
  schemas:
    API Key:
      type: object
      properties:
        _id:
          type: string
          description: The key itself
        appID:
          type: string
          description: Human readable description of the key
        death:
          type: integer
          default: -1
          description: Unix timestamp of the planned death of the key. If -1, there is no planned death, but may be retired at any time without notice.
        features:
          type: object
          description: A Map[string]boolean describing the allowed functions of the key. The given defaults are the features implemented by base stupid-backend and may be extended for extended features (such as data retrieval).
          default:
            log: true
            registeredUsers: true
            sendCrash: true
            backend: false
    Registered User:
      type: object
      properties:
        _id:
          type: string
          description: UUID of the user
        username:
          type: string
        password:
          type: string
          format: password
          description: argon2ID 32 byte hashed password. Base64 Encoded.
        salt:
          type: string
          description: 16 byte salt. Base64 Encoded.
        email:
          type: string
          format: email
paths:
  /features:
    description: Get the details of the API Key, including it's capabilities
    get:
      responses:
        '200':
          description: Returns the API Key itself
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/API Key"